name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Debug output directory
        run: |
          echo "Current directory contents:"
          ls -al
          echo "Build directory contents (if exists):"
          ls -al build || echo "Build directory does not exist!"
          echo "Output directory contents (if exists):"
          ls -al output || echo "Output directory does not exist!"

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_KEY }}
        with:
          source-directory: 'output' # build 또는 output에 맞게 변경
          destination-github-username: 'seung365'
          destination-repository-name: 'alphamail-frontend'
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL}}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
