name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Prepare output directory
        run: |
          mkdir -p output
          cp -r build/* output/
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: 'seung365'
          destination-repository-name: 'alphamail-frontend'
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL}}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
